# Generated by go2rpm 1
%bcond_without check

# https://github.com/blevesearch/segment
%global goipath         github.com/blevesearch/segment
%global commit          762005e7a34fd909a84586299f1dd457371d36ee

%global debug_package   %{nil}

%gometa

%global common_description %{expand:
A Go library for performing Unicode Text Segmentation as described in Unicode
Standard Annex #29.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A Go library for performing Unicode Text Segmentation as described in Unicode Standard Annex #29

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/segment %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Jan 26 04:57:25 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0-0.1.20200126git762005e
- Initial package
- Disable debug information package
